### PR TITLE
Add support for Cisco IOS config files

### PR DESCRIPTION
**Pull request by alextremblay**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Sorry for the slow reply, you need to also update the README to add a section about these files.

By the way, what does this have to do with "IOS"?

**Comment by samuelcolvin** [comment]
Hi @saschalalala, looking good, few more things to do:
* add another section to the README with information about this language/file type
* as per #97 which I recently merged, you might want to rebase and add another `breakpoint` item

**Comment by alextremblay** [comment]
ok, rebased and updated as requested :)

Please take a look and let me know if there's anything else

**Comment by samuelcolvin** [comment]
Looks great, thanks so much.

I'll release a new version soon.

**Pull request merged**
