### PR TITLE
Add support for TOML files

### LINKED ISSUE #34: Add support for TOML files
Would be nice if support for `.toml.j2` could be added as well.

### PR DESCRIPTION
**Pull request by Hipska**
I have tested it and it seems to work (this is my first contribution to a vscode extension).

Fixes #34

### CODE REVIEW

**Comment by samuelcolvin** [comment]
looks good to me, please can you update history and version and I'll release.

**Comment by Hipska** [comment]
I've allowed maintainers to push. You can do it..

Or what should the new version be? It is quite uncommon that PR's also produce new version.

**Comment by samuelcolvin** [comment]
Not all at, every change should be included in history/changleog.

May as well increment the minor version.

**Comment by samuelcolvin** [comment]
okay, you didn't update history and the version you incremented to on already existed.

But I've fixed it and deploy.

**Comment by Hipska** [comment]
That's exactly the reason why it's bad practice to let that be done in feature PR's..

PS. You might want to have a look at GitFlow.

**Comment by samuelcolvin** [comment]
I disagree, the person working on the code should be responsible for updating history, the real solution is something like [towncrier](https://pypi.org/project/towncrier/) but that's overkill for a project like this.

But thanks for the contribution.

**Pull request merged**
