### PR TITLE
add JS/TS support and document it

### PR DESCRIPTION
**Pull request by OmarTawfik**
Following the footsteps of #43
Please let me know if there is anything else I can do.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
cc @samuelcolvin

**Comment by OmarTawfik** [comment]
cc @samuelcolvin I wonder if this is still actively maintained?

**Comment by samuelcolvin** [comment]
sorry, been busy.

I'll try to do a release soon.

**Comment by OmarTawfik** [comment]
@samuelcolvin no worries at all. thank you for working on this awesome extension!

**Comment by OmarTawfik** [comment]
@samuelcolvin I wonder if there is a date for the next VS Code marketplace release. Please let me know if there is anything I can do to help. No pressure of course. Thanks for the awesome extension!

**Comment by OmarTawfik** [comment]
@samuelcolvin I wonder if we can do a new release with this fix?
Thanks!

**Comment by user114145** [comment]
Yea, that would be nice. 
Now I'm manually updating the installed version with this commit every time XD
But I get it. I'm really bad at picking old projects back up for minor fixers myself.

**Pull request merged**
