### PR TITLE
recognize include file templates for C++

### PR DESCRIPTION
**Pull request by dmose**
Thanks for a very helpful extension!  

Right now, the extension doesn't recognize C++ include files by default. This adds .h.* files to the list...

### CODE REVIEW

**Comment by samuelcolvin** [comment]
looks good, can you update the readme as well.

**Comment by dmose** [comment]
Done!

**Comment by dmose** [comment]
@samuelcolvin any idea when you might get the bandwidth to merge this (and, ideally, cut a release?)

Thanks!

**Comment by samuelcolvin** [comment]
sorry for the delay, both done.

**Comment by dmose** [comment]
No worries; thanks so much!

**Pull request merged**
