### PR TITLE
Adds support for systemd unit files (#30)

### PR DESCRIPTION
**Pull request by joshreep**
@samuelcolvin I came across this issue and thought I'd submit a PR.  I'm not sure how to test the syntax out, but the code seems right from looking at the other examples.  You can test it out and make adjustments if you want, or you can let me know know to test it and I'll confirm.  Thanks.

### CODE REVIEW

**Comment by joshreep** [comment]
@samuelcolvin I figured out how to test it.  Should be good to go.

**Comment by samuelcolvin** [comment]
Fixes #30.

Looks good to me, I'll review fully and deploy next week when I'm in the office.

Could you add a new section to history?

**Comment by joshreep** [comment]
Sure.  I'll add that right now.

**Comment by joshreep** [comment]
@samuelcolvin Done.

**Comment by samuelcolvin** [comment]
great, thank you. Will release now.

**Pull request merged**
